[
  {
    "personId": "12345",
    "lastName": "Pryde",
    "radioNumber": "A-1",
    "firstName": "Kathryn",
    "stationNumber": "(all)",
    "stationName": "(all)",
    "dob": "",
    "workPhone": "707-555-1234",
    "mobilePhone": "707-555-2345",
    "startDate": "",
    "gender": "Female",
    "street": "1123 Xavier School Drive",
    "city": "Watkinsville",
    "zip": "30677",
    "state": "GA",
    "region": "",
    "position": "Chief",
    "isActive": "",
    "isEmployee: ""
  },
  {
    "personId": "54321",
    "lastName": "Rasputin",
    "radioNumber": "841",
    "firstName": "Piotr",
    "stationNumber": "8",
    "stationName": "",
    "dob": "",
    "workPhone": "",
    "mobilePhone": "206-555-9876",
    "startDate": "",
    "gender": "Male",
    "street": "A31 Mother Russia Road",
    "city": "Seattle",
    "zip": "98133",
    "state": "WA",
    "region": "",
    "position": "",
    "isActive": "",
    "isEmployee: ""
  },
  {
    "personId": "56789",
    "lastName": "Worthington",
    "radioNumber": " 122",
    "firstName": "Warren III",
    "stationNumber": "1",
    "stationName": "",
    "dob": "",
    "workPhone": "706-555-3945",
    "mobilePhone": "",
    "startDate": "",
    "gender": "Male",
    "street": "1140 Experiment Station Rd",
    "city": "Watkinsville",
    "zip": "",
    "state": "GA",
    "region": "",
    "position": "",
    "isActive": "",
    "isEmployee: ""
  }
]
